#!/usr/bin/env python3

# © Thomas Schmeiduch <https://github.com/schtho>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

import sys
import requests
import getopt

VERSION = '1.0'
OPT_MERAKI_APIKEY = None
OPT_MERAKI_ORG = None
OPT_MERAKI_TAGS = None
OPT_MERAKI_TAG_TYPE = None

def meraki(organization_id, api_key, network_tags, tag_filter_any):

    payload = None

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "X-Cisco-Meraki-API-Key": api_key
    }

    # Get all Meraki Networks (optional by tags)
    meraki_net_list = get_meraki_networks(payload, headers, organization_id, network_tags, tag_filter_any)

    # Get all alerts provided by Meraki Cloud
    meraki_org_assurance_alerts_by_network_id = get_meraki_org_assurance_alerts_by_network_id(payload, headers, organization_id)

    # for each given Meraki network
    for meraki_net in meraki_net_list:
        net_id = meraki_net["id"]
        net_name = meraki_net["name"]

        # Get all alerts of given Meraki network
        all_alerts_of_network_list = meraki_org_assurance_alerts_by_network_id[
            net_id] if net_id in meraki_org_assurance_alerts_by_network_id else []

        # Piggyback CMK Host
        cmk_host = f"<<<<Meraki-{net_name}>>>>\n"
        sys.stdout.write(cmk_host)
        # Service Beginning
        sys.stdout.write('<<<meraki_alerts:sep(59)>>>\n')

        for alert in all_alerts_of_network_list:

            alert_category_type = alert["categoryType"] if "categoryType" in alert else "None"
            alert_device_type = alert["deviceType"] if "deviceType" in alert else "None"
            alert_type = alert["type"] if "type" in alert else "None"
            alert_title = alert["title"] if "title" in alert else "None"
            alert_severity = alert["severity"] if "severity" in alert else "None"

            alert_devices = ""
            if "scope" in alert:
                if "devices" in alert["scope"]:
                    for device in alert["scope"]["devices"]:
                        alert_devices += f"{device},"
            if alert_devices == "":
                alert_devices = "None"

            sys.stdout.write("%s;%s;%s;%s;%s;%s\n" % (
                alert_category_type,
                alert_device_type,
                alert_type,
                alert_title,
                alert_severity,
                alert_devices
            ))


def get_meraki_networks(payload, headers, organization_id, network_tags, tag_filter_any):
    #    url = f"https://api.meraki.com/api/v1/organizations/{organization_id}/networks?tags[]=paedagogik&tags[]=verwaltung&tagsFilterType=withAnyTags"
    url = f"https://api.meraki.com/api/v1/organizations/{organization_id}/networks"
    if len(network_tags) != 0:
        if tag_filter_any:
            url += "?tagsFilterType=withAnyTags"
        else:
            url += "?tagsFilterType=withAllTags"
        for t in network_tags:
            url += f"&tags[]={t}"

    response = requests.request('GET', url, headers=headers, data = payload)

    if response.status_code == 429:
        raise Exception("API rate limit exceeded")

    meraki_net_list = response.json()

    return meraki_net_list


def get_meraki_org_assurance_alerts_by_network_id(payload, headers, organization_id):
    url = f"https://api.meraki.com/api/v1/organizations/{organization_id}/assurance/alerts/"
    response = requests.request('GET', url, headers=headers, data=payload)
    json_org_alerts = response.json()

    alerts_by_network_id_dict = {}
    alerts_by_network_id_dict.setdefault(key, [])

    for alert in json_org_alerts:
        if "network" in alert:
            net_id = alert["network"].id
            net_name = alert["network"].name

            alerts_by_network_id_dict[net_id].append(alert)
        else:
            continue

    return alerts_by_network_id_dict


def usage():
    sys.stderr.write("""Checkmk Cisco Meraki Alerts Agent
USAGE: agent_meraki_alerts -o ORGANIZATION-ID -k API-KEY -n NETWORK-ID
       agent_meraki_alerts -h
OPTIONS:
  -h, --help                                Show this help message and exit
  -o, --organization                        Organization ID inside Meraki Cloud
  -k, --key                                 Cloud API-Key
  -t, --tags                                Meraki Network Tags Filter
  -tt, --tagtype                            True if any of given --tags (filter), otherwise if all given tags
""")

def cli_args():
    opt_key = None
    opt_org = None
    opt_tags = None
    opt_tag_type = None

    short_options = "hk:o:t:tt:"
    long_options = ["help", "key=", "organization=", "tags=", "tagtype="]

    try:
        opts, args = getopt.getopt(sys.argv[1:], short_options, long_options)
    except getopt.GetoptError as err:
        sys.stderr.write("%s\n" % err)
        sys.exit(1)

    for opt, arg in opts:
        if opt in ['-h', '--help']:
            usage()
            sys.exit(0)
        elif opt in ["-k", "--key"]:
            opt_key = arg
        elif opt in ["-o", "--organization"]:
            opt_org = arg
        elif opt in ["-t", "--tags"]:
            opt_tags = arg
        elif opt in ["-tt", "--tagtype"]:
            opt_tag_type = arg
        elif not opt:
            usage()
            sys.exit(0)

    if not opt_org:
        sys.stderr.write("ERROR: No organization defined.\n")
        sys.exit(1)
    elif not opt_key:
        sys.stderr.write("ERROR: No key given.\n")
        sys.exit(1)

    return opt_org, opt_key, opt_tags, opt_tag_type


# MAIN FUNCTION

org, key, tags, tag_type = cli_args()
OPT_MERAKI_APIKEY = key
OPT_MERAKI_ORG = org
OPT_MERAKI_TAGS = tags
OPT_MERAKI_TAG_TYPE = tag_type

sys.stdout.write('<<<check_mk>>>\n')
sys.stdout.write('Version: %s\n' % VERSION)
sys.stdout.write('AgentOS: meraki_alerts\n')

sys.stdout.write('<<<labels>>>\n')
sys.stdout.write('{"cmk/device":"meraki"}\n')

tag_list = OPT_MERAKI_TAGS.split(",")
meraki(OPT_MERAKI_ORG, OPT_MERAKI_APIKEY, tag_list, OPT_MERAKI_TAG_TYPE)
