#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# © Thomas Schmeiduch <https://github.com/schtho>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def agent_meraki_arguments(params, hostname, ipaddress):
    args = []
    if params["org_id"] != "":
        args.extend(
            [
                "-o",
                params["org_id"]
            ]
        )
    if params["api_key"] != "":
        args.extend(
            [
                "-k",
                params["api_key"]
            ]
        )
    if ("filter_tags" in params) and (len(params["filter_tags"]) != 0):
        args.extend(
            [
                "-t",
                ','.join(params["filter_tags"])
            ]
        )
    if ("tags_filter_type" in params) and (params["tags_filter_type"] != None):
        args.extend(
            [
                "-tt",
                str(params["tags_filter_type"])
            ]
        )

    args.extend(["%s" % ipaddress])
    return args


special_agent_info["meraki_alerts"] = agent_meraki_arguments
